version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: SentryCubeDB
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SentryCubeDB
    logging:
      options:
        max-size: 10m
        max-file: "3"
    # volumes:
      # - postgres_data:/var/lib/postgresql/data

# volumes:
  # postgres_data: